--VIEW THE DATA

SELECT * FROM DBO.['portfolio sql1$']

-- '*' SYMBOL FOR SHOW ALL COLUMNS
--SHOW SELECTED COLUMNS

SELECT Domain,[Job titiles] from dbo.['portfolio sql1$'] --USE SQUARE BRACKETS WHEN COLUMN NAME HAS SPACE

SELECT * FROM DBO.['portfolio sql1$']	-- 'ORDER BY USED TO SORT THE VALUES IN ACENDING ORDER & CHAR[A-Z]'
ORDER BY Domain,Tasks

SELECT Domain,SUM(Tasks) AS TOTAL_TASK	-- TOTALLY AFFECTED DOMAINS AND TOTAL TASKS
FROM DBO.['portfolio sql1$']
GROUP BY Domain

SELECT [Job titiles],SUM(Tasks) AS TOTAL_TASK	-- TOTALLY AFFECTED JOBS AND TOTAL TASKS
FROM DBO.['portfolio sql1$']
GROUP BY [Job titiles]

SELECT Domain,SUM(AI_Workload_Ratio) AS TOTAL_PERCENTAGE	-- IT SHOWS TOTAL WORK PERCENTAGE OF AI BASED ON DOMAINS
FROM DBO.['portfolio sql1$']
GROUP BY Domain

SELECT Domain,SUM([AI models]) AS TOTAL_MODELS	-- IT SHOWS TOTAL MODELS USED IN CORRESBONDING DOMAIN
FROM DBO.['portfolio sql1$']
GROUP BY Domain

SELECT [Job titiles],SUM(AI_Workload_Ratio*100) AS TOTAL_PERCENTAGE	-- IT SHOWS TOTAL WORK PERCENTAGE OF AI BASED ON JOBS
FROM DBO.['portfolio sql1$']
GROUP BY [Job titiles]

SELECT [Job titiles],SUM(AI_Workload_Ratio*100) AS TOTAL_PERCENTAGE	-- IT SHOWS THE JOB WHICH IS ABOVE 40% WORKED BY AI MODELS
FROM DBO.['portfolio sql1$']
WHERE (AI_Workload_Ratio*100) > 40
GROUP BY [Job titiles]

-- BASED ON DOMAIN SHOWS TOTAL TASK,MODEL,IMPACT AND PERCENTAGE

SELECT Domain,SUM(Tasks) AS TOTAL_TASK,
SUM([AI Impact]) AS TOTAL_IMPACT, 
SUM([AI models]) AS TOTAL_MODELS,			
SUM(AI_Workload_Ratio) AS TOTAL_PERCENTAGE	
FROM DBO.['portfolio sql1$']
GROUP BY Domain